# -*- mode: python ; coding: utf-8 -*-
# Auto-generated spec file for TimerApp release build

# Analysis configuration
a = Analysis(
    [r'C:\Users\LENOVO\Desktop\cp50\timer\main.py'],
    pathex=[r'C:\Users\LENOVO\Desktop\cp50\timer'],
    binaries=[],
    datas=[
        (r'C:\Users\LENOVO\Desktop\cp50\timer\icon.ico', '.'),
        (r'C:\Users\LENOVO\Desktop\cp50\timer\media_player_settings.json', '.'),
        (r'C:\Users\LENOVO\Desktop\cp50\timer\links.txt', '.')
    ],
    hiddenimports=[
        'timer_app',
        'timer_app.factories',
        'timer_app.factories.app_factory',
        'timer_app.application',
        'timer_app.application.services',
        'timer_app.application.interfaces',
        'timer_app.domain',
        'timer_app.domain.models',
        'timer_app.infrastructure',
        'timer_app.infrastructure.storage',
        'timer_app.ui',
        'timer_app.ui.views',
        'timer_app.ui.widgets',
        'timer_app.ui.widgets.buttons',
        'timer_app.ui.widgets.close_button',
        'timer_app.ui.widgets.display_widgets',
        'timer_app.ui.widgets.logs_panel',
        'timer_app.ui.widgets.loop_controls',
        'timer_app.ui.widgets.media_player_button',
        'timer_app.ui.widgets.menu_button',
        'timer_app.ui.widgets.notes_window',
        'timer_app.ui.window_manager',
        'timer_app.audio',
        'timer_app.audio.factory',
        'timer_app.audio.interfaces',
        'timer_app.audio.loop_controller',
        'timer_app.audio.loop_manager',
        'timer_app.audio.monitor',
        'timer_app.audio.player',
        'timer_app.audio.playlist',
        'timer_app.audio.system',
        'pygame',
        'pygame.mixer',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'mutagen',
        'mutagen.id3',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.simpledialog',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'IPython',
        'notebook',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='TimerApp_v1.0.0',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=[r'C:\Users\LENOVO\Desktop\cp50\timer\icon.ico'],
)
